<?php
return array (
  'bjyun' => 
  array (
    'status' => '1',
    'from' => 'bjyun',
    'show' => '解析2',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://jx.xmflv.com/?url=',
    'parse2' => 'https://jx.xmflv.com/?url=',
    'sort' => '9999',
    'tip' => '无需安装任何插件',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'bjyun',
  ),
  'bjm3u8' => 
  array (
    'status' => '1',
    'from' => 'bjm3u8',
    'show' => '解析3',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://jx.xmflv.com/?url=',
    'parse2' => 'https://jx.xmflv.com/?url=',
    'sort' => '9999',
    'tip' => '无需安装任何插件',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'bjm3u8',
  ),
  'slm3u8' => 
  array (
    'status' => '1',
    'from' => 'slm3u8',
    'show' => '森林资源',
    'des' => '支持手机电脑在线播放',//1
    'ps' => '1',
    'parse' => 'https://jx.xmflv.com/?url=',
    'parse2' => 'https://jx.xmflv.com/?url=',
    'sort' => '19999',
    'tip' => '无需安装任何插件',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'slm3u8',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '解析1',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://jx.xmflv.com/?url=',
    'parse2' => 'https://jx.xmflv.com/?url=',
    'sort' => '9999',
    'tip' => '无需安装任何插件',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'qq',
  ),
  'wjm3u8' => 
  array (
    'status' => '1',
    'from' => 'wjm3u8',
    'show' => '无尽①',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'http://23.249.29.117/static/player/artplayer.html?url=',
    'sort' => '1194',
    'tip' => '无需安装任何插件',
    'id' => 'wjm3u8',
  ),
  'hnm3u8' => 
  array (
    'status' => '1',
    'from' => 'hnm3u8',
    'show' => '红牛在线',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'http://23.249.29.117/static/player/artplayer.html?url=',
    'sort' => '1193',
    'tip' => '无需安装任何插件',
    'id' => 'hnm3u8',
  ),
  'bfzym3u8' => 
  array (
    'status' => '1',
    'from' => 'bfzym3u8',
    'show' => '暴风资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'http://23.249.29.117/static/player/artplayer.html?url=',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'bfzym3u8',
  ),
  'heimuer' => 
  array (
    'status' => '1',
    'from' => 'heimuer',
    'show' => '黑木耳资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'http://23.249.29.117/static/player/artplayer.html?url=',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'heimuer',
  ),
  'ruyi' => 
  array (
    'status' => '1',
    'from' => 'ruyi',
    'show' => '如意资源2',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'http://23.249.29.117/static/player/artplayer.html?url=',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'ruyi',
  ),
  'rym3u8' => 
  array (
    'status' => '1',
    'from' => 'rym3u8',
    'show' => '如意资源1',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'http://23.249.29.117/static/player/artplayer.html?url=',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'rym3u8',
  ),
  // 'bjyun' => 
  // array (
  //   'status' => '1',
  //   'from' => 'subm3u8',
  //   'show' => '解析1',
  //   'des' => '支持手机电脑在线播放',
  //   'target' => '_self',
  //   'ps' => '0',
  //   'parse' => 'https://jx.xmflv.com/?url=',
  //   'sort' => '1000',
  //   'tip' => '无需安装任何插件',
  //   'id' => 'subm3u8',
  // ),
  'yym3u8' => 
  array (
    'status' => '1',
    'from' => 'yym3u8',
    'show' => '鸭鸭资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'http://23.249.29.117/static/player/artplayer.html?url=',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'yym3u8',
  ),
  'tkm3u8' => 
  array (
    'status' => '1',
    'from' => 'tkm3u8',
    'show' => 'tkm3u8播放器',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://122.228.8.29:4433/xmflv.js',
    'parse2' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'tkm3u8',
  ),
  'tkyun' => 
  array (
    'status' => '1',
    'from' => 'tkyun',
    'show' => 'tkyun播放器',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://122.228.8.29:4433/xmflv.js',
    'parse2' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'kernel' => '0',
    'features' => '.*?.mp4,.*?.m3u8',
    'headers' => '',
    'issethead' => '',
    'id' => 'tkyun',
  ),
);